export const IMG = {
  Navigation: {
    BottomNavigation: require('../Assets/BottomNavigation.png'),
    NavBottom: require('../Assets/navbottom.png'),
    BackRec: require('../Assets/backRel.png'),
    BackLogo: require('../Assets/3x.png'),
  },
  CompanyLogo: {
    logoSmall: require('../Assets/1xK1Receipt.png'),
    logoMedium: require('../Assets/2xK1Receipt.png'),
    logoBig: require('../Assets/3xK1Receipt.png'),
  },
  ArrowIcons: {
    RightArrow: require('../Assets/rightarrow.png'),
    DownArrow: require('../Assets/downarrow.png'),
  },
  ValueIcons: {
    Basic: require('../Assets/icons/basic.png'),
    Extended: require('../Assets/icons/extended.png'),
    Silver: require('../Assets/icons/silver.png'),
    Gold: require('../Assets/icons/gold.png'),
    Premium: require('../Assets/icons/premium.png'),
  },
  ExtraLogo: {
    paypal: require('../Assets/paypallogo.png'),
    googlelogo: require('../Assets/googlelogo.png'),
    profilePIc: require('../Assets/profilepic.png'),
    editButton: require('../Assets/editButton.png'),
    SmallProfilePic: require('../Assets/smallProfilePic.png'),
    settings: require('../Assets/settings.png'),
    Filelogo: require('../Assets/filelogo.png'),
    Camearlogo: require('../Assets/cameralogo.png'),
    DownArrow: require('../Assets/downarrow2.png'),
    RightArrow: require('../Assets/rightarrow2.png'),
    DownArrow3: require('../Assets/downarrow3.png'),
    BankReceipt: require('../Assets/bankReceipt.png'),
    EditRed: require('../Assets/editred.png'),
    DeleteRed: require('../Assets/deletered.png'),
    CloseCategory: require('../Assets/close.png'),
    RoundChart: require('../Assets/roundChart.png'),
    Calender: require('../Assets/calender.png'),
    Hlines: require('../Assets/hLines.png'),
    Vlines: require('../Assets/vLines.png'),
    companyLogo: require('../Assets/companyLogo.png'),
  },
  BottomIcon: {
    Budget: require('../Assets/bottomNav/budget.png'),
    Expense: require('../Assets/bottomNav/expense.png'),
    Analytics: require('../Assets/bottomNav/analytics.png'),
    Profile: require('../Assets/bottomNav/profile.png'),
    Scan: require('../Assets/bottomNav/scan.png'),
  },
};
